### ISSUE TITLE
请问data中的第4列数据表示什么？

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#11]
作者您好，我在尝试将我的数据按照本文方法的数据格式进行组织，但是我不知道本文数据格式第4列表示什么，请问能否作说明？
![QQ图片20230814171856](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/7c1f7496-88cc-4125-aa98-60d6d901bf5f)
我目前可以大致猜到第1列表示root推文的id，也表示这棵树的id，第2列表示该条推文的parent node是哪条推文，None表示没有parent node（即root），第3列表示该条推文在这棵树结构中的id，第5列表示tweet or reply的具体内容。但是第4列我猜不到表示什么，我在仔细阅读文章后仍没找到答案，请问作者能否解答。

**Comment by DanielLin97** [comment]
Thank you for your issue. It's a placeholder for your further customized usage, or you could just ignore it.
