### ISSUE TITLE
src/processors.py缺少内容

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#4]
您好，我按照指示运行train.sh，在运行到dataset.py的时候需要导入src/processors.py里的median_mapping，但是我查看了一下processors.py里缺少该内容。以下是报错信息：
```
Traceback (most recent call last):
  File "D:\zeroRumor_AAAI-main\run.py", line 19, in <module>
    from src.dataset import FewShotDataset
  File "D:\zeroRumor_AAAI-main\src\dataset.py", line 14, in <module>
    from src.processors import processors_mapping, num_labels_mapping, output_modes_mapping, compute_metrics_mapping, \
ImportError: cannot import name 'median_mapping' from 'src.processors' (D:\zeroRumor_AAAI-main\src\processors.py) 
```

**Comment by zjc-code** [comment]
估计不会补上的

**Comment by DanielLin97** [comment]
Actually, there is no need to supplement that part. It could be easily found out that src.processors median_mapping is not used in the uploaded version of our code if read the code in dataset.py. Alternatively, you could delete it yourself. Thank you for your question.

**Comment by zjc-code** [comment]
> Actually, there is no need to supplement that part. It could be easily found out that src.processors median_mapping is not used in the uploaded version of our code if read the code in dataset.py. Alternatively, you could delete it yourself. Thank you for your question.

![image](https://user-images.githubusercontent.com/66833970/235344886-5971d786-e5dd-40c1-b108-da5b8dd70ce8.png)
不对啊这不是有吗median_mapping

**Comment by DanielLin97** [comment]
> > Actually, there is no need to supplement that part. It could be easily found out that src.processors median_mapping is not used in the uploaded version of our code if read the code in dataset.py. Alternatively, you could delete it yourself. Thank you for your question.
> 
> ![image](https://user-images.githubusercontent.com/66833970/235344886-5971d786-e5dd-40c1-b108-da5b8dd70ce8.png) 不对啊这不是有吗median_mapping

It's not used during our running process, that is, that part will not be run in the logic of our code. As shown in the screenshot, our task never runs into this part of the code. If you run into and failed at this part with exceptions, please provide more detailed information about your errors.
<img width="812" alt="fd81dcbbc63927d00fb5a200796d510" src="https://user-images.githubusercontent.com/31728535/235679073-71785ed2-dd52-4316-bab8-c85b6595ad23.png">

**Comment by DanielLin97** [comment]
> > Actually, there is no need to supplement that part. It could be easily found out that src.processors median_mapping is not used in the uploaded version of our code if read the code in dataset.py. Alternatively, you could delete it yourself. Thank you for your question.
> 
> ![image](https://user-images.githubusercontent.com/66833970/235344886-5971d786-e5dd-40c1-b108-da5b8dd70ce8.png) 不对啊这不是有吗median_mapping

Also, you can find that it's designed for regression tasks instead of the classification task in our work.
<img width="679" alt="872f679c6387f296a207a761ec69e28" src="https://user-images.githubusercontent.com/31728535/235679878-5a6b8949-3482-4268-96e3-2e90f6455f25.png">

**Comment by zjk000** [comment]
@zjc-code 哥们请问你跑起来了吗？我下载下来什么都没改直接跑run.py出现这个问题
```
D:\anaconda3\envs\python3.9\python.exe D:/zeroRumor_AAAI-main/run.py
Traceback (most recent call last):
  File "D:\zeroRumor_AAAI-main\run.py", line 726, in <module>
    main()
  File "D:\zeroRumor_AAAI-main\run.py", line 320, in main
    parser = HfArgumentParser((ModelArguments, DynamicDataTrainingArguments, DynamicTrainingArguments))
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 144, in __init__
    self._add_dataclass_arguments(dtype)
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 271, in _add_dataclass_arguments
    self._parse_dataclass_field(parser, field)
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 215, in _parse_dataclass_field
    kwargs["type"] = field.type.__args__[0]
AttributeError: type object 'list' has no attribute '__args__'
```
