### ISSUE TITLE
缺少src/models.py文件

### ISSUE THREAD

**Issue by sugarcandy** [PengyaoYi/zeroRumor_AAAI#5]
看到您的代码再次更新真的太高兴了，但是在我将数据集下载完准备运行的时候，发现提示缺少src.models文件，如图所示。
![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/40589172/fa28d486-2497-474c-a2bc-767c917cd931)
烦请您百忙之中得空上传一下，万分感谢！！！

**Comment by DanielLin97** [comment]
Thank you for your issue. That part could be just ignored and annotated out. We would further organize our code to avoid redundant and unnecessary imports.

**Comment by zjk000** [comment]
哥们，请问你能跑起来吗？我直接下载下来，什么也没修改，直接运行那个run.py就出现这个问题
```
D:\anaconda3\envs\python3.9\python.exe D:/zeroRumor_AAAI-main/run.py
Traceback (most recent call last):
  File "D:\zeroRumor_AAAI-main\run.py", line 726, in <module>
    main()
  File "D:\zeroRumor_AAAI-main\run.py", line 320, in main
    parser = HfArgumentParser((ModelArguments, DynamicDataTrainingArguments, DynamicTrainingArguments))
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 144, in __init__
    self._add_dataclass_arguments(dtype)
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 271, in _add_dataclass_arguments
    self._parse_dataclass_field(parser, field)
  File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 215, in _parse_dataclass_field
    kwargs["type"] = field.type.__args__[0]
AttributeError: type object 'list' has no attribute '__args__'
```

**Comment by sugarcandy** [comment]
> 哥们，请问你能跑起来吗？我直接下载下来，什么也没修改，直接运行那个run.py就出现这个问题
> 
> ```
> D:\anaconda3\envs\python3.9\python.exe D:/zeroRumor_AAAI-main/run.py
> Traceback (most recent call last):
>   File "D:\zeroRumor_AAAI-main\run.py", line 726, in <module>
>     main()
>   File "D:\zeroRumor_AAAI-main\run.py", line 320, in main
>     parser = HfArgumentParser((ModelArguments, DynamicDataTrainingArguments, DynamicTrainingArguments))
>   File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 144, in __init__
>     self._add_dataclass_arguments(dtype)
>   File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 271, in _add_dataclass_arguments
>     self._parse_dataclass_field(parser, field)
>   File "D:\anaconda3\envs\python3.9\lib\site-packages\transformers\hf_argparser.py", line 215, in _parse_dataclass_field
>     kwargs["type"] = field.type.__args__[0]
> AttributeError: type object 'list' has no attribute '__args__'
> ```

我没有跑起来
