### ISSUE TITLE
What do "1" and "0" mean?

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#6]
Hi, thank you for providing the Arabic and Cantonese datasets in the paper. I have one small question though, what do "1" and "0" mean in, for example, zeroRumor_AAAI/data/Cantonese/data_new_label.txt? Does "1" mean that source tweet is a rumor and "0" mean that source tweet is a non-rumor?

**Comment by DanielLin97** [comment]
Thank you for your question. Sorry for your confusion. Yeah, it is as you said that "1" mean that the source tweet is a rumor and "0" mean that the source tweet is a non-rumor.
