### ISSUE TITLE
请问能否说明一下代码的逻辑？

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#9]
作者你好，抱歉多次打扰你。我希望将该代码改成用在我自己的数据集上，但我读了代码以后不知道从何改起，以及我对该代码有一些疑惑，希望能得到作者的指导。我在以下问题描述中如果有理解不到位的地方烦请作者指正。

论文采用一系列方法在source dataset上训练得到两个prototypical verbalizer，按照论文zero-shot的设定，接下来就应该是用这两个训练好的prototypical verbalizer在target datasets上直接进行测试。但是我将代码运行起来后，看到的是训练过程，且连续训练了四十多个小时后仍未结束，于是我手动终止了程序（应该是因为我的GPU不够）。

让我不解的地方在于，在README中有一个'pretrain-model'，我不确定这里的pretrain指的是原始的预训练好的xlm-roberta还是指在论文中经过source dataset训练之后的。如果是原始的xlm-roberta，那的确应该用source dataset先训练，但是整个项目中只包含了target datasets，并没有source dataset，为什么运行代码后能够训练起来呢？如果是经过source dataset训练后的模型，那为什么运行起来后还需要训练呢？不应该直接用target dataset来测试吗？

虚心向作者请教（我不确定作者更习惯阅读中文还是英文，如果更习惯阅读英文的话please let me know）。

**Comment by Tiantian20000321** [comment]
> 作者你好，抱歉多次打扰你。我希望将该代码改成用在我自己的数据集上，但我读了代码以后不知道从何改起，以及我对该代码有一些疑惑，希望能得到作者的指导。我在以下问题描述中如果有理解不到位的地方烦请作者指正。
> 
> 论文采用一系列方法在source dataset上训练得到两个prototypical verbalizer，按照论文zero-shot的设定，接下来就应该是用这两个训练好的prototypical verbalizer在target datasets上直接进行测试。但是我将代码运行起来后，看到的是训练过程，且连续训练了四十多个小时后仍未结束，于是我手动终止了程序（应该是因为我的GPU不够）。
> 
> 让我不解的地方在于，在README中有一个'pretrain-model'，我不确定这里的pretrain指的是原始的预训练好的xlm-roberta还是指在论文中经过source dataset训练之后的。如果是原始的xlm-roberta，那的确应该用source dataset先训练，但是整个项目中只包含了target datasets，并没有source dataset，为什么运行代码后能够训练起来呢？如果是经过source dataset训练后的模型，那为什么运行起来后还需要训练呢？不应该直接用target dataset来测试吗？
> 
> 虚心向作者请教（我不确定作者更习惯阅读中文还是英文，如果更习惯阅读英文的话please let me know）。

![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/121372157/40c0fe52-697f-4b05-a5f0-32214b25a83f)
请问你是更新之后就能运行了吗

**Comment by zjk000** [comment]
> > 作者你好，抱歉多次打扰你。我希望将该代码改成用在我自己的数据集上，但我读了代码以后不知道从何改起，以及我对该代码有一些疑惑，希望能得到作者的指导。我在以下问题描述中如果有理解不到位的地方烦请作者指正。
> > 论文采用一系列方法在source dataset上训练得到两个prototypical verbalizer，按照论文zero-shot的设定，接下来就应该是用这两个训练好的prototypical verbalizer在target datasets上直接进行测试。但是我将代码运行起来后，看到的是训练过程，且连续训练了四十多个小时后仍未结束，于是我手动终止了程序（应该是因为我的GPU不够）。
> > 让我不解的地方在于，在README中有一个'pretrain-model'，我不确定这里的pretrain指的是原始的预训练好的xlm-roberta还是指在论文中经过source dataset训练之后的。如果是原始的xlm-roberta，那的确应该用source dataset先训练，但是整个项目中只包含了target datasets，并没有source dataset，为什么运行代码后能够训练起来呢？如果是经过source dataset训练后的模型，那为什么运行起来后还需要训练呢？不应该直接用target dataset来测试吗？
> > 虚心向作者请教（我不确定作者更习惯阅读中文还是英文，如果更习惯阅读英文的话please let me know）。
> 
> ![image](https://user-images.githubusercontent.com/121372157/258558251-40c0fe52-697f-4b05-a5f0-32214b25a83f.png) 请问你是更新之后就能运行了吗

是的。你下载README的那个模型然后放到当前目录下了吗？像这样
![QQ截图20230805112645](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/605aa6cf-05de-49b9-b948-a6bc38076d78)

**Comment by Tiantian20000321** [comment]
![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/121372157/90f37baa-0e01-4406-9006-8bc7633eb66c)
我是这样的

**Comment by zjk000** [comment]
> ![image](https://user-images.githubusercontent.com/121372157/258560465-90f37baa-0e01-4406-9006-8bc7633eb66c.png) 我是这样的

那我能想到的就是HuggingFace的transformers包的问题了，这俩玩意经常犯病，把AutoTokenizer改成XLMRobertaTokenizer可能有用

**Comment by Tiantian20000321** [comment]
> 
![image](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/121372157/3ed3aa39-cda5-43b2-9463-ee255293f00b)
我改了还是报这个错，请问你有遇到过吗

**Comment by zjk000** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/121372157/258568376-3ed3aa39-cda5-43b2-9463-ee255293f00b.png) 我改了还是报这个错，请问你有遇到过吗

遇到过，但是我全部换成最新版本的代码就没有这个问题了

**Comment by Tiantian20000321** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121372157/258568376-3ed3aa39-cda5-43b2-9463-ee255293f00b.png) 我改了还是报这个错，请问你有遇到过吗
> 
> 遇到过，但是我全部换成最新版本的代码就没有这个问题了

我就是使用上周更新后的还是这样

**Comment by zjk000** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/121372157/258568376-3ed3aa39-cda5-43b2-9463-ee255293f00b.png) 我改了还是报这个错，请问你有遇到过吗
> > 
> > 
> > 遇到过，但是我全部换成最新版本的代码就没有这个问题了
> 
> 我就是使用上周更新后的还是这样

看你这报错信息感觉是因为你加载成了TensorFlow的模型呢？应该是加载PyTorch模型才对

**Comment by Tiantian20000321** [comment]
> > > > > 
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/121372157/258568376-3ed3aa39-cda5-43b2-9463-ee255293f00b.png) 我改了还是报这个错，请问你有遇到过吗
> > > 
> > > 
> > > 遇到过，但是我全部换成最新版本的代码就没有这个问题了
> > 
> > 
> > 我就是使用上周更新后的还是这样
> 
> 看你这报错信息感觉是因为你加载成了TensorFlow的模型呢？应该是加载PyTorch模型才对

我改错中要求装tensorflow我就装了

**Comment by Tiantian20000321** [comment]
> > > 作者你好，抱歉多次打扰你。我希望将该代码改成用在我自己的数据集上，但我读了代码以后不知道从何改起，以及我对该代码有一些疑惑，希望能得到作者的指导。我在以下问题描述中如果有理解不到位的地方烦请作者指正。
> > > 论文采用一系列方法在source dataset上训练得到两个prototypical verbalizer，按照论文zero-shot的设定，接下来就应该是用这两个训练好的prototypical verbalizer在target datasets上直接进行测试。但是我将代码运行起来后，看到的是训练过程，且连续训练了四十多个小时后仍未结束，于是我手动终止了程序（应该是因为我的GPU不够）。
> > > 让我不解的地方在于，在README中有一个'pretrain-model'，我不确定这里的pretrain指的是原始的预训练好的xlm-roberta还是指在论文中经过source dataset训练之后的。如果是原始的xlm-roberta，那的确应该用source dataset先训练，但是整个项目中只包含了target datasets，并没有source dataset，为什么运行代码后能够训练起来呢？如果是经过source dataset训练后的模型，那为什么运行起来后还需要训练呢？不应该直接用target dataset来测试吗？
> > > 虚心向作者请教（我不确定作者更习惯阅读中文还是英文，如果更习惯阅读英文的话please let me know）。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/121372157/258558251-40c0fe52-697f-4b05-a5f0-32214b25a83f.png) 请问你是更新之后就能运行了吗
> 
> 是的。你下载README的那个模型然后放到当前目录下了吗？像这样 ![QQ截图20230805112645](https://user-images.githubusercontent.com/103090972/258560363-605aa6cf-05de-49b9-b948-a6bc38076d78.png)

你那个目录结构下的config.json文件是从那个下载的xlm-model里移出来的吗

**Comment by zjk000** [comment]
> > > > 作者你好，抱歉多次打扰你。我希望将该代码改成用在我自己的数据集上，但我读了代码以后不知道从何改起，以及我对该代码有一些疑惑，希望能得到作者的指导。我在以下问题描述中如果有理解不到位的地方烦请作者指正。
> > > > 论文采用一系列方法在source dataset上训练得到两个prototypical verbalizer，按照论文zero-shot的设定，接下来就应该是用这两个训练好的prototypical verbalizer在target datasets上直接进行测试。但是我将代码运行起来后，看到的是训练过程，且连续训练了四十多个小时后仍未结束，于是我手动终止了程序（应该是因为我的GPU不够）。
> > > > 让我不解的地方在于，在README中有一个'pretrain-model'，我不确定这里的pretrain指的是原始的预训练好的xlm-roberta还是指在论文中经过source dataset训练之后的。如果是原始的xlm-roberta，那的确应该用source dataset先训练，但是整个项目中只包含了target datasets，并没有source dataset，为什么运行代码后能够训练起来呢？如果是经过source dataset训练后的模型，那为什么运行起来后还需要训练呢？不应该直接用target dataset来测试吗？
> > > > 虚心向作者请教（我不确定作者更习惯阅读中文还是英文，如果更习惯阅读英文的话please let me know）。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/121372157/258558251-40c0fe52-697f-4b05-a5f0-32214b25a83f.png) 请问你是更新之后就能运行了吗
> > 
> > 
> > 是的。你下载README的那个模型然后放到当前目录下了吗？像这样 ![QQ截图20230805112645](https://user-images.githubusercontent.com/103090972/258560363-605aa6cf-05de-49b9-b948-a6bc38076d78.png)
> 
> 你那个目录结构下的config.json文件是从那个下载的xlm-model里移出来的吗

那个应该没关系，那个是我之前自己下的xlm-roberta的

**Comment by zjk000** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/121372157/258568376-3ed3aa39-cda5-43b2-9463-ee255293f00b.png) 我改了还是报这个错，请问你有遇到过吗
> > > > 
> > > > 
> > > > 遇到过，但是我全部换成最新版本的代码就没有这个问题了
> > > 
> > > 
> > > 我就是使用上周更新后的还是这样
> > 
> > 
> > 看你这报错信息感觉是因为你加载成了TensorFlow的模型呢？应该是加载PyTorch模型才对
> 
> 我改错中要求装tensorflow我就装了

应该是没跑对吧，我跑的时候没让我装tensorflow

**Comment by sugarcandy** [comment]
stack expects a non-empty TensorList
 你们有遇到这个问题吗？

**Comment by Tiantian20000321** [comment]
> stack expects a non-empty TensorList 你们有遇到这个问题吗？

重新下载后没有遇到

**Comment by zjk000** [comment]
已解决

**Comment by zjk000** [comment]
已解决
